name: Build OpenShockClock

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-gobject
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-gcc

      - name: Install Python dependencies
        run: |
          pip install requests python-dotenv pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "icons:icons" openshockclock-gtk.py

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenShockClock-Windows
          path: |
            dist/*.exe
            README.md
            LICENSE
